### ISSUE TITLE
建议为本科毕业论文单独设立一个分支

### ISSUE THREAD

**Issue by Tiyanki** [registor/nwafuthesis#3]
老师好，动医学院学生的编码能力没有达到预期的水平，推广仍困难，建议进一步精简模板，添加更低级的注释，以方便向本科生推广使用。

**Comment by registor** [comment]
谢谢你的关注的建议，目前流行趋势是将本硕博写在一起，以便于模板的维护。

对于LaTeX，还是应该有学习成本的，以后得听选修课，勤于练习才好。

期待明天会更好。
