### ISSUE TITLE
二、三、四级标题问题

### ISSUE THREAD

**Issue by wmgselfblog** [registor/nwafuthesis#4]
根据信息工程学院官网下载的“1信息学院本科毕业论文撰写规范及打印排版要求.doc“中第 2 至 3 页的浅蓝色内容，二、三级标题应段前空两个字，四级标题则无此要求。耿老师5月31日发布的2.2.12版本则是“二、三级标题**无**段前空两个字，四级标题空两个字“。不知我对此句排版要求的理解是否正确。

另四级标题的括号应是**中文状态下半角括号**

如有对排版要求的误解，抱歉打扰耿老师了。

**Comment by registor** [comment]
教务处通知与学院有少许不一致，目前是双轨运行，按模板设置排版即可。

**Comment by wmgselfblog** [comment]
好的老师 谢谢了
